=== berislavlopac/waexplorer/source/tree/watree.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XML Spy v4.4 U (http://www.xmlspy.com)-->
<!ELEMENT tree (item+)>
<!ATTLIST tree
	base CDATA #IMPLIED
>
<!ELEMENT item (title, action?, icon?, item*)>
<!ATTLIST item
	context CDATA #IMPLIED
	subsrc CDATA #IMPLIED
	id CDATA #IMPLIED
>
<!ELEMENT title (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ELEMENT icon (#PCDATA)>

=== berislavlopac/waexplorer/tree/tree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Berislav Lopac (WA Research) -->
<!DOCTYPE tree SYSTEM "watree.dtd">
<tree base="../../biosScan12db/template/">
	<item context="link">
		<title>Inspect software</title>
		<icon>soft.gif</icon>
		<item context="brlj">
			<title>Licence management</title>
			<action>programs/programsall.xml?page=1</action>
			<icon>soft.gif</icon>
		</item>
		<item>
			<title>Excluded from licence management</title>
			<action>programs/excluded_software.xml</action>
			<icon>soft.gif</icon>
		</item>
	</item>
	<item>
		<title>Computers</title>
		<action>servers/serversall.xml</action>
		<icon>cgrp.gif</icon>
		<item>
			<title>Unsuccessful logins</title>
			<icon>error.gif</icon>
		</item>
		<item subsrc="db_groups.xml">
			<title>Groups</title>
			<action>groups/groups.xml</action>
		</item>
		<item context="generic" subsrc="db_segments.xml">
			<title>Network segments</title>
			<action>networkscan/netscans.xml</action>
			<icon>cgrp.gif</icon>
		</item>
		<item context="generic" subsrc="oses.xml">
			<title>By operating system</title>
			<icon>cgrp.gif</icon>
		</item>
	</item>
	<item>
		<title>Settings</title>
		<action>application/settings.xml</action>
		<icon>sett.gif</icon>
	</item>
</tree>

=== berislavlopac/waexplorer/tree/oses.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Berislav Lopac (WA Research) -->
<!DOCTYPE tree SYSTEM "watree.dtd">
<tree base="../../biosScan12db/template/">
	<item context="generic">
		<title>Windows 2000</title>
		<action>servers/serversall.xml</action>
		<icon>comp.gif</icon>
	</item>
	<item context="generic">
		<title>Windows XP</title>
		<icon>comp.gif</icon>
	</item>
	<item context="generic">
		<title>Windows NT</title>
		<icon>comp.gif</icon>
	</item>
	<item context="generic">
		<title>Windows 9x</title>
		<icon>comp.gif</icon>
	</item>
	<item context="generic">
		<title>Other</title>
		<icon>comp.gif</icon>
	</item>
</tree>

=== berislavlopac/waexplorer/tree/waresearch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Berislav Lopac (WA Research) -->
<!DOCTYPE tree SYSTEM "watree.dtd">
<tree base="http://www.lopsica.com/">
	<item context="link">
		<title>Home</title>
		<action>default.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link" id="aboutus">
		<title>About us</title>
		<icon>folder.gif</icon>
		<item context="link">
			<title>What WA</title>
			<action>about.htm</action>
			<icon>htm.gif</icon>
		</item>
		<item context="link">
			<title>Team</title>
			<action>team.htm</action>
			<icon>htm.gif</icon>
		</item>
	</item>
	<item context="link">
		<title>Products</title>
		<action>products/default.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>Partners</title>
		<action>partners.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link" id="jobs">
		<title>Jobs</title>
		<action>jobs/default.htm</action>
		<icon>folder.gif</icon>
		<item context="link" subsrc="positions.xml" id="positions">
			<title>Positions</title>
			<action>jobs/positions.htm</action>
			<icon>folder.gif</icon>
		</item>
		<item context="link">
			<title>Selection</title>
			<action>jobs/selection.htm</action>
			<icon>htm.gif</icon>
		</item>
		<item context="link">
			<title>Join us</title>
			<action>jobs/join.asp</action>
			<icon>htm.gif</icon>
		</item>
	</item>
</tree>

=== berislavlopac/waexplorer/tree/positions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.4 U (http://www.xmlspy.com) by Berislav Lopac (WA Research) -->
<!DOCTYPE tree SYSTEM "watree.dtd">
<tree base="http://www.wa-research.com/">
	<item context="link">
		<title>XML/C++ SuperGuru</title>
		<action>jobs/jobs.xcsg.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>C++ Developer</title>
		<action>jobs/jobs.jcpg.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>DHTML Scripter</title>
		<action>jobs/jobs.xdtm.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>Education/Documentation specialist</title>
		<action>jobs/jobs.ueds.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>Software Product Architect</title>
		<action>jobs/jobs.spar.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>Project Management Coordinator</title>
		<action>jobs/jobs.pmco.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>Production Artist</title>
		<action>jobs/jobs.paop.htm</action>
		<icon>htm.gif</icon>
	</item>
	<item context="link">
		<title>Product Manager</title>
		<action>jobs/jobs.pmch.htm</action>
		<icon>htm.gif</icon>
	</item>
</tree>
