=== berislavlopac/waexplorer/source/menus/wamenus.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT menu (itemsgroup+)>
<!ATTLIST menu
	type (menu | menubar | toolbar) "menu"
>
<!ELEMENT itemsgroup (item+)>
<!ELEMENT item (title, action, icon?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT action (#PCDATA)>
<!ATTLIST action
	type CDATA #IMPLIED
	context CDATA #IMPLIED
>
<!ELEMENT icon (#PCDATA)>

=== berislavlopac/waexplorer/bars/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "../menus/wamenus.dtd">
<menu type="menubar">
	<itemsgroup>
		<item>
			<title>File</title>
			<action>generic</action>
		</item>
		<item>
			<title>Edit</title>
			<action>submenu</action>
		</item>
		<item>
			<title>Navigate</title>
			<action>submenu</action>
		</item>
		<item>
			<title>Help</title>
			<action>generic</action>
		</item>
	</itemsgroup>
</menu>

=== berislavlopac/waexplorer/bars/tool.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "../menus/wamenus.dtd">
<menu type="toolbar">
	<itemsgroup>
		<item>
			<title>Home</title>
			<action>alert('home');</action>
			<icon>comp.gif</icon>
		</item>
		<item>
			<title>Search</title>
			<action>alert('search');</action>
			<icon>cgrp.gif</icon>
		</item>
		<item>
			<title>Settings</title>
			<action>alert('settings');</action>
			<icon>soft.gif</icon>
		</item>
	</itemsgroup>
	<itemsgroup>
		<item>
			<title>Help</title>
			<action>alert('help');</action>
			<icon>sett.gif</icon>
		</item>
	</itemsgroup>
</menu>

=== berislavlopac/waexplorer/source/menus/generic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "wamenus.dtd">
<menu>
	<itemsgroup>
		<item>
			<title>Naslov 1: sad malo isprobavam da vidim koliko ovo može biti dugačko</title>
			<action type="url">Ovo je neka akcija</action>
			<icon>comp</icon>
		</item>
		<item>
			<title>Naslov 2</title>
			<action type="url">http://www.incanus.com</action>
		</item>
		<item>
			<title>Naslov 3</title>
			<action type="script">javascript:void(0);</action>
		</item>
		<item>
			<title>Google</title>
			<action type="url">http://www.google.com</action>
		</item>
	</itemsgroup>
	<itemsgroup>
		<item>
			<title>Ovo ima submenu</title>
			<action type="submenu">submenu</action>
		</item>
		<item>
			<title>Naslov 5</title>
			<action type="url">Ovo je neka akcija</action>
		</item>
	</itemsgroup>
	<itemsgroup>
		<item>
			<title>Test 1: ovo je druga grupa</title>
			<action type="url">Ovo je neka akcija</action>
		</item>
	</itemsgroup>
	<itemsgroup>
		<item>
			<title>Naslov 77</title>
			<action type="url">Ovo je neka akcija</action>
		</item>
		<item>
			<title>Naslov 895</title>
			<action type="url">Ovo je neka akcija</action>
			<icon>cgrp</icon>
		</item>
		<item>
			<title>Naslov 99</title>
			<action type="url">Ovo je neka akcija</action>
		</item>
		<item>
			<title>Naslov 10.000</title>
			<action type="url">Ovo je neka akcija</action>
		</item>
	</itemsgroup>
</menu>

=== berislavlopac/waexplorer/source/menus/link.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "wamenus.dtd">
<menu>
	<itemsgroup>
		<item>
			<title>Ovo je menu pod nazivom "link".</title>
			<action type="script">void(0);</action>
		</item>
		<item>
			<title>Ako me klikneš &lt;b&gt;eksplodirat ću.&lt;/b&gt;</title>
			<action type="script">alert('BOOM!');</action>
		</item>
		<item>
			<title>Ovo zuji.</title>
			<action type="script">alert('ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ');</action>
		</item>
	</itemsgroup>
	<itemsgroup>
		<item>
			<title>Neki manji naslov</title>
			<action type="script">alert("njanja")</action>
		</item>
		<item>
			<title>Još jednom: ovo je LINK!</title>
			<action type="url">http://www.incanus.com</action>
		</item>
	</itemsgroup>
	<itemsgroup>
		<item>
			<title>Insert new item...</title>
			<action type="script">modifyTreeItem(2,top.waMenuInstance.opener);</action>
		</item>
		<item>
			<title>Edit this item...</title>
			<action type="script">modifyTreeItem(1,top.waMenuInstance.opener);</action>
		</item>
		<item>
			<title>Delete this item...</title>
			<action type="script">modifyTreeItem(0,top.waMenuInstance.opener);</action>
		</item>
	</itemsgroup>
</menu>

=== berislavlopac/waexplorer/bars/default.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "../menus/wamenus.dtd">
<menu type="menubar">
	<itemsgroup>
		<item>
			<title>File</title>
			<action>generic</action>
		</item>
		<item>
			<title>Edit</title>
			<action>subitem</action>
		</item>
		<item>
			<title>Default</title>
			<action>subitem</action>
		</item>
		<item>
			<title>Default</title>
			<action>generic</action>
		</item>
	</itemsgroup>
</menu>

=== berislavlopac/waexplorer/source/menus/submenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "wamenus.dtd">
<menu>
	<itemsgroup>
		<item>
			<title>Ovo je menu pod nazivom "link".</title>
			<action type="script">void(0);</action>
		</item>
		<item>
			<title>Ako me klikneš &lt;b&gt;eksplodirat ću.&lt;/b&gt;</title>
			<action type="script">alert('BOOM!');</action>
			<icon>comp</icon>
		</item>
		<item>
			<title>Ovo zuji.</title>
			<action type="script">alert('ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ');</action>
		</item>
	</itemsgroup>
	<itemsgroup>
		<item>
			<title>Neki manji naslov</title>
			<action type="submenu" context="link">alert("njanja")</action>
			<icon>soft</icon>
		</item>
		<item>
			<title>Još jednom: ovo je LINK!</title>
			<action type="url">http://www.incanus.com</action>
		</item>
	</itemsgroup>
</menu>
